

export interface Total {
    cases: number;
    deaths: number;
    recovered: number;
    updated: number;
    active: number;
}


// Generated by https://quicktype.io

export interface Countrys {
    country: string;
    countryInfo: CountryInfo;
    cases: number;
    todayCases: number;
    deaths: number;
    todayDeaths: number;
    recovered: number;
    active: number;
    critical: number;
    casesPerOneMillion: number | null;
    deathsPerOneMillion: number | null;
}

export interface CountryInfo {
    _id: number | null;
    country?: string;
    iso2: null | string;
    iso3: null | string;
    lat: number;
    long: number;
    flag: string;
}


export interface HistoryCountry {
    country: string;
    timeline: Timeline;
}

export interface Timeline {
    cases: { [key: string]: number };
    deaths: { [key: string]: number };
    recovered: { [key: string]: number };
}



